[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "BPD"
authors = [{ name = "Ismael Mendoza" }]
description = "Bayesian Pixel Domain method for shear inference."
version = "0.0.1"
license = { file = "LICENSE" }
readme = "README.md"
dependencies = [
    "numpy >=1.18.0",
    "galsim >=2.3.0",
    "jax",
    "jaxlib",
    "blackjax>=1.2.0",
]

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
home = "https://github.com/LSSTDESC/BPD"

[tool.setuptools.packages.find]
include = ["bpd*"]


[tool.flake8]
max-line-length = 88
ignore = ["C901", "E203", "W503"]
per-file-ignores = ["__init__.py:F401"]


[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88 # black default
